version: 2
parameters:
         repo:
            type: string
            default: c30m_fdk
         branch:
            type: string
            default: feature
            
jobs:
    testjob:
        docker:
            - image: cimg/base:2021.11
        steps:
            - run: 
                name: install dependencies
                command: | 
                    ls -a
                    export myname="chandu"
                    echo "Code worked"
                    echo $myname
                    sudo apt-get update && sudo apt-get install curl -y
                    
            - run:
                name: Trigger Linux Build
                command: |
                  echo ' Configured Env Variable "$myname" '
                  #curl --request POST --url https://circleci.com/api/v2/project/gh/pamarthich/jyothsnatest/pipeline --header "Circle-Token: $CIRCLECI_API_KEY" --header "content-type: application/json" --data '{"branch":"main", "parameters": {"mynamingo": "'${myname}'"}}'

workflows:
    version: 2
    test:
        jobs:
            - testjob:
                context: vars

#     test:
#         triggers:
#           - schedule:
#                 cron: "30 9,10,11,12 * * *"
#                 filters:
#                   branches: 
#                     only:
#                       - mugiwaranoluffy


#         jobs:
#             - testjob
                   
    
