version: 2
jobs:
    #jobs
    job-1:
        #executors  (container, Linux, Windows and macos)
        # docker:
        #     - image: alpine:3.7
        steps:
            - checkout
            # - run: echo "Hello World"
            # mvn build 
    job-2:
        docker:
            - image: alpine:3.7
        steps:
            - run: 
                command: | 
                    ls -a
                    echo "Code worked"

        

workflows:
    version: 2
    test:
        jobs:
            - job-1
                filters:
                    branches:
                        only:
                            - /release\/.*/   #release
                            - /feature\/.*/  /release*/
                        ignore:
                            - /master
            - Hold-for-Approval:
                type: approval
                
            - job-2:
                requires:
                    - Hold-for-Approval
                   
    