version: 2
jobs:
    testjob:
        docker:
            - image: alpine:3.7
        steps:
            - run: 
                command: | 
                    ls -a
                    echo "Code worked"

        

workflows:
    version: 2
    test:
        triggers:
          - schedule:
            cron: "30 9,10,11 * * *"
               filters:
                 branches: 
                    only:
                      - test


        jobs:
            - testjob
                   
    
