version: 2
jobs:
    #jobs
    job-1:
        #executors  (container, Linux, Windows and macos)
        docker:
            - image: alpine:3.7
        steps:
            - checkout
            # - run: echo "Hello World"
    job-2:
        docker:
            - image: alpine:3.7
        steps:
            - run: 
                command: | 
                    ls -a
                    echo "Code worked"

        

workflows:
    version: 2
    test:
        jobs:
            - job-1
            - Hold-for-Approval:
                type: approval
                requires:
                    - job-1
            - job-2:
                requires:
                    - Hold-for-Approval
    