version: 2
parameters:
         repo:
            type: string
            default: c30m_fdk
         branch:
            type: string
            default: feature
            
jobs:
    testjob:
        docker:
            - image: alpine:3.7
        steps:
            - run: 
                command: | 
                    ls -a
                    echo "Code worked"

        

workflows:
    version: 2
    test:
        jobs:
            - testjob
        when:
            equal: << pipeline.parameters >>
#     test:
#         triggers:
#           - schedule:
#                 cron: "30 9,10,11,12 * * *"
#                 filters:
#                   branches: 
#                     only:
#                       - mugiwaranoluffy


#         jobs:
#             - testjob
                   
    
