version: 2
jobs:
    testjob:
        docker:
            - image: alpine:3.7
        steps:
            - run: 
                command: | 
                    ls -a
                    echo "Code worked"

        

workflows:
    version: 2
    test:
        triggers:
          - schedule:
               cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *"
               filters:
                 branches: 
                    only:
                      - test


        jobs:
            - testjob
                   
    
