version: 2
parameters:
         repo:
            type: string
            default: c30m_fdk
         branch:
            type: string
            default: feature
            
jobs:
    testjob:
        docker:
            - image: cimg/base:2021.11
        steps:
            - run: 
                command: | 
                    ls -a
                    echo "Code worked"
            - run:
                command: |
                  curl --request POST --url https://circleci.com/api/v2/project/gh/zmarkan/pinging-me-softly/pipeline \ 
                       --header "Circle-Token: $CIRCLECI_API_KEY" \
                       --header "content-type: application/json" \
                       --data '{"branch":"main"}'

workflows:
    version: 2
    test:
        jobs:
            - testjob:
                context: vars

#     test:
#         triggers:
#           - schedule:
#                 cron: "30 9,10,11,12 * * *"
#                 filters:
#                   branches: 
#                     only:
#                       - mugiwaranoluffy


#         jobs:
#             - testjob
                   
    
